### ISSUE TITLE
Thanks for the good work!

### ISSUE THREAD

**Issue by MohamedRejeb** [Vidi005/Tajweed-Recognition#1]
Hello brother,
Jazaka allahou kahyran.
We will use your script to add tajweed styling.

Let me know if you need any help.

**Comment by Vidi005** [comment]
Thank you sir. You can use my script for your apps/programs. 😊

**Comment by Vidi005** [comment]
> Hello brother, Jazaka allahou kahyran. We will use your script to add tajweed styling.
> 
> Let me know if you need any help.

Hello sir, I will inform you that my tajweed recognition project may not be maintained later because there are still many bugs and conflicting tajweed rules. It's too complex for determining tajweed rules using regular expression patterns.

I recommend to use [Quran.com API](https://api-docs.quran.com/docs/quran.com_versioned/4.0.0/quran-verses-uthmani-tajweed/) for implementing tajweed rules.
